In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
a+b
a.sum(axis=0)
a.sum(axis=1)
b.sum(axis=0)
b.sum(axis=1)

array([18, 27])

In [13]:
b=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b.size
b.ndim
b.itemsize
b.dtype

dtype('int32')

In [21]:
k=np.linspace(1,5,3)
k=np.linspace(1,10,20)
k.shape
k.reshape(4,5)
k.ravel()
k.shape

(20,)

In [28]:
k=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
k.shape
l=k.ravel()
l.shape
l.reshape((6,2))
l.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
l.min()
l.max()
a=l.reshape((4,3))
b=np.arange(1,13,1)
m=b.reshape(4,3)
a+m

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [41]:
k=np.array([[1,2,3],[4,5,6],[7,8,9]])
k.sum(axis=0)
k.sum(axis=1)

array([ 6, 15, 24])

In [43]:
h=np.linspace(1,10,20)
h

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [57]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
a[1][0]
a[1][1]
a[1][2]
a[0][1]
a[0][0]
a[0][2]
a[2][0]
a[2][1]
a[2][2]
a[0][-1]
a[1][-1]
a[2][-1]
a[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [58]:
a[:,-1]

array([2, 5, 8])

In [59]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[10,11,12]])
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11, 12]])

In [60]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
k=np.arange(30).reshape(2,15)
np.hsplit(k,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [66]:
a=np.array([[1,2,3],[3,4,5],[8,9,10]])
b=a>4
a[b]

array([ 5,  8,  9, 10])

In [67]:
a[b]=-1

In [68]:
a

array([[ 1,  2,  3],
       [ 3,  4, -1],
       [-1, -1, -1]])